# Generated by Django 5.2.3 on 2025-06-20 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('game_preferences', models.CharField(blank=True, max_length=255, verbose_name='Игровые предпочтения')),
                ('skill_level', models.CharField(blank=True, max_length=50, verbose_name='Уровень навыков')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная анкета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Анкета пользователя',
                'verbose_name_plural': 'Анкеты пользователей',
            },
        ),
    ]
