# Generated by Django 5.2.2 on 2025-06-06 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='desc',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='default_text', verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название игры')),
                ('cover', models.ImageField(upload_to='game_covers/', verbose_name='обложка игры')),
                ('users', models.ManyToManyField(related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Игроки')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы применить никнейи из стима', max_length=60, verbose_name='Ник')),
                ('hours', models.FloatField(verbose_name='Наиграно часов')),
                ('rang', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ранг')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questionnaires', to='main.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questionnaires', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
        ),
    ]
